# Use postgres/example user/password credentials
# docker-compose -f stack.yml up

version: '3.1'

services:

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: password
      PGDATA: /tmp
    ports:
      - 5432:5432
    volumes:
    - ./postgresdata:/tmp



