# Use postgres/example user/password credentials
# docker-compose -f stack.yml up

version: '3.1'

services:

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: password
      PGDATA: /tmp
    ports:
      - 5432:5432
    volumes:
    - ./postgresdata:/var/lib/postgresql/data  
    



#docker exec -it <container_name> bash
#psql -U postgres
#create database dvdrental;
#exit
#pg_restore -U postgres -d dvdrental Desktop/dvdrental.tar

# these are in the data folder
# psql -U postgres
# CREATE DATABASE readychef;
# \q
#  psql -U postgres readychef < readychef.sql
# repeat for other dbs

