# Use postgres/example user/password credentials
# docker-compose -f stack.yml up

version: '3.1'

services:

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: password
      PGDATA: /tmp
    ports:
      - 5432:5432
    volumes:
    - ./postgresdata:/tmp
    - ./SQL:/SQL
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:8080/tcp
    environment:
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - PGADMIN_LISTEN_PORT=8080
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
    volumes:
      - ./pgdata:/var/lib/postgresql/data 

